name: Java CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build & Install checkstyle-config
        run: cd checkstyle-config && mvn -B clean install && cd ..
      - name: Build root
        run: mvn -B clean verify
      - name: Test lint
        run: cd test && mvn -B -P lint clean verify
